- name: Apply k8s configuration
  hosts: node
  become: yes
  tasks:
    - name: Create new deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml
      register: deployment_result
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Debug deployment result
      debug:
        var: deployment_result.stdout

    - name: Create new service
      command: kubectl apply -f /home/ubuntu/service.yml
      register: service_result
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Debug service result
      debug:
        var: service_result.stdout

   
