kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: sivasankarrr/dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80

